[package]
authors = ["Alex Moon <alex@moonspot.org>"]
description = "Crate name reserved for the nrf-sdc project"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "nrf-sdc"
repository = "https://github.com/alexmoon/nrf-sdc"
version = "0.0.0"

[dependencies]
