[workspace]
resolver = "2"
members = [
    "nrf-mpsl",
    "nrf-mpsl-sys",
    "nrf-sdc",
    "nrf-sdc-sys",
]

[patch.crates-io]
embassy-nrf = { git = "https://github.com/embassy-rs/embassy", tag = "embassy-executor-v0.1.1" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", tag = "embassy-executor-v0.1.1"}
